package cn.jason.mybatis.plugin;

import org.mybatis.generator.api.FullyQualifiedTable;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.api.dom.xml.*;

import java.util.*;

public class PageableFindPlugin extends PageablePlugin {
	private boolean hadAddXml = false;
	private Map<FullyQualifiedTable, List<XmlElement>> elementsToAdd;

	public PageableFindPlugin() {
		elementsToAdd = new HashMap<FullyQualifiedTable, List<XmlElement>>();
	}

	public boolean validate(List<String> warnings) {
		return true;
	}

	@Override
	public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method,
	                                                             Interface interfaze, IntrospectedTable introspectedTable) {
		if (introspectedTable.getTargetRuntime() == IntrospectedTable.TargetRuntime.MYBATIS3) {
			copyAndAddMethod(method, interfaze);
		}
		return true;
	}

	@Override
	public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(
			Method method, Interface interfaze,
			IntrospectedTable introspectedTable) {
		if (introspectedTable.getTargetRuntime() == IntrospectedTable.TargetRuntime.MYBATIS3) {
			copyAndAddMethod(method, interfaze);
		}
		return true;
	}

	@Override
	public boolean sqlMapSelectByExampleWithoutBLOBsElementGenerated(
			XmlElement element, IntrospectedTable introspectedTable) {
		if (introspectedTable.getTargetRuntime() == IntrospectedTable.TargetRuntime.MYBATIS3) {
			copyAndSaveElement(element, introspectedTable.getFullyQualifiedTable());
		}
		return true;
	}

	@Override
	public boolean sqlMapSelectByExampleWithBLOBsElementGenerated(
			XmlElement element, IntrospectedTable introspectedTable) {
		if (introspectedTable.getTargetRuntime() == IntrospectedTable.TargetRuntime.MYBATIS3) {
			copyAndSaveElement(element, introspectedTable.getFullyQualifiedTable());
		}
		return true;
	}

	/**
	 * We'll override this method and add any new elements generated by
	 * previous calls
	 */
	@Override
	public boolean sqlMapDocumentGenerated(Document document,
	                                       IntrospectedTable introspectedTable) {
		document.getRootElement().getElements().add(2, addWhereClause(document));

		List<XmlElement> elements = elementsToAdd.get(introspectedTable.getFullyQualifiedTable());
		if (elements != null) {
			for (XmlElement element : elements) {
				document.getRootElement().addElement(element);
			}
		}

		return true;
	}

	private XmlElement addWhereClause(Document document) {
		for (Element rootElement : document.getRootElement().getElements()) {
			if (rootElement instanceof XmlElement) {
				XmlElement root = (XmlElement) rootElement;
				if (root.getName().equals("sql") && root.getAttributes().size() == 1) {
					if (root.getAttributes().get(0).getValue().equals("Example_Where_Clause")) {

						XmlElement newElement = new XmlElement("sql");
						newElement.addAttribute(new Attribute("id", "Example_Where_Clause_With_Alias"));
						XmlElement where = new XmlElement("where");
						XmlElement whereContent = new XmlElement(((XmlElement) ((XmlElement) root.getElements().get(root.getElements().size() - 1)).getElements().get(0)));
						for (Iterator<Attribute> iterator = whereContent.getAttributes().iterator(); iterator.hasNext(); ) {
							Attribute attribute = iterator.next();
							if (attribute.getName().equals("collection")) {
								iterator.remove();
							}
						}
						whereContent.addAttribute(new Attribute("collection", "example.oredCriteria"));
						where.addElement(whereContent);
						newElement.addElement(where);
						return newElement;
					}
				}
			}
		}
		throw new IllegalStateException("mapper xml里不包含Example_Where_Clause节点");
	}


	private void copyAndAddMethod(Method method, Interface interfaze) {
		Method newMethod = new Method(method);
		newMethod.setName(method.getName() + "WithPage"); //$NON-NLS-1$
		Parameter oriParameter = method.getParameters().get(0);
		newMethod.getParameters().clear();
		newMethod.addParameter(new Parameter(oriParameter.getType(), oriParameter.getName(), "@Param(\"example\")"));
		newMethod.addParameter(createPageParameter()); //$NON-NLS-1$
		interfaze.addMethod(newMethod);
		interfaze.addImportedType(pageType);
	}

	private void copyAndSaveElement(XmlElement element, FullyQualifiedTable fqt) {
		XmlElement newElement = new XmlElement(element);

		// remove old id attribute and add a new one with the new name
		for (Iterator<Attribute> iterator = newElement.getAttributes().iterator(); iterator.hasNext(); ) {
			Attribute attribute = iterator.next();
			if ("id".equals(attribute.getName())) { //$NON-NLS-1$
				iterator.remove();
				Attribute newAttribute = new Attribute("id", attribute.getValue() + "WithPage"); //$NON-NLS-1$ //$NON-NLS-2$
				newElement.addAttribute(newAttribute);
				break;
			}
		}
		removeType(newElement);
		removeOrderElement(newElement);
		replaceDistinct(element);
		replaceWhere(newElement);
		appendOrder(newElement);
		appendLimit(newElement);
		//TODO 处理Example_Where_Clause

		// save the new element locally.   We'll add it to the document
		// later
		List<XmlElement> elements = elementsToAdd.get(fqt);
		if (elements == null) {
			elements = new ArrayList<XmlElement>();
			elementsToAdd.put(fqt, elements);
		}
		elements.add(newElement);
	}

	private void replaceWhere(XmlElement element) {
		for (Element innerElement : element.getElements()) {
			if (innerElement instanceof XmlElement) {
				XmlElement xmlElement = (XmlElement) innerElement;
				if (xmlElement.getName().equals("if") && xmlElement.getAttributes().size() == 1) {
					if (xmlElement.getAttributes().get(0).getValue().equals("_parameter != null")) {
						xmlElement.getAttributes().clear();
						xmlElement.addAttribute(new Attribute("test", "example != null"));
						xmlElement.getElements().clear();
						XmlElement includeElement = new XmlElement("include");
						includeElement.addAttribute(new Attribute("refid", "Example_Where_Clause_With_Alias"));
						xmlElement.addElement(includeElement);
					}
				}
			}
		}
	}

	private void replaceDistinct(XmlElement element) {
		for (Element innerElement : element.getElements()) {
			if (innerElement instanceof XmlElement) {
				XmlElement xmlElement = (XmlElement) innerElement;
				if (xmlElement.getName().equals("if") && xmlElement.getElements().size() == 1) {
					Element childElement = xmlElement.getElements().get(0);
					if (childElement instanceof TextElement) {
						TextElement textElement = (TextElement) childElement;
						if (textElement.getContent().equals("distinct")) {
							xmlElement.getAttributes().clear();
							xmlElement.getAttributes().add(new Attribute("test", "example.distinct"));
							break;
						}
					}
				}
			}
		}
	}

	private void appendOrder(XmlElement newElement) {
		XmlElement pageElement = new XmlElement("if");
		pageElement.addAttribute(new Attribute("test", "example.orderByClause != null"));
		pageElement.addElement(new TextElement("order by ${example.orderByClause}"));
		newElement.addElement(pageElement);
	}

	private void removeOrderElement(XmlElement newElement) {
		removeXmlElement(newElement, "if", "order by ${orderByClause}");
	}
}
